package uk.ashleybye.rxkotlin.operatorstransformations.vacation

import uk.ashleybye.rxkotlin.operatorstransformations.location.City
import java.util.*

/**
 * Holds hotel information.
 *
 * Holds information about a hotel. The name is generated by concatenating a given title, city and
 * the word "Hotel". The cost is randomly generated.
 *
 * @constructor initialise the name and cost of the hotel
 * @param title - the partial title of the hotel
 * @param city - the city in which the hotel resides
 * @property name - the generated name of the hotel
 * @property cost - the randomly generated cost of the hotel
 */
data class Hotel(private val title: String, private val city: City) {
    companion object {
        private val random = Random()
        val partialNames = listOf("Regency", "Continental", "Ritz", "Hilton", "Travel Lodge",
                "Easy Rest", "Emporium", "World View", "Sweet Escape", "Dingy", "Paradise",
                "Nasty", "Drury", "Holiday Inn", "Marriott", "Shangri-La", "Millennium",
                "Dorchester", "Ritz-Carlton", "Premier Inn")
    }

    val name = "$city $title Hotel"
    val cost = Math.round(random.nextFloat() * 500)

    override fun toString() = "$name: £$cost"
}
